rm ./Custom_To_RIFCS/ACU/CustomFunctions.xsl
rm ./Custom_To_RIFCS/BOND/CustomFunctions.xsl
rm ./Custom_To_RIFCS/UniversityOfWollongong/CustomFunctions.xsl
rm ./Custom_To_RIFCS/UWA/CustomFunctions.xsl
rm ./DDI_To_RIFCS/ADA/CustomFunctions.xsl
rm ./ISO19115-3_To_RIFCS/AURIN/CustomFunctions.xsl
rm ./ISO19115-3_To_RIFCS/GA/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/AIMS/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/AODN/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/BOM/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/CityFutures/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/EATLAS/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/IMAS/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/IMOS/CustomFunctions.xsl
rm ./ISO19139_To_RIFCS/NCI/CustomFunctions.xsl
rm ./OAI_DC_To_RIFCS/CentralQueenslandUniversity/CustomFunctions.xsl
rm ./OAI_DC_To_RIFCS/MonashFigshare/CustomFunctions.xsl
rm ./RDF_To_RIFCS/MonashFigshare/CustomFunctions.xsl
rm ./ISO19115-3_To_RIFCS/GA/CustomFunctionsGMD.xsl
rm ./ISO19139_To_RIFCS/AIMS/CustomFunctionsGMD.xsl
rm ./ISO19139_To_RIFCS/AODN/CustomFunctionsGMD.xsl
rm ./ISO19139_To_RIFCS/BOM/CustomFunctionsGMD.xsl
rm ./ISO19139_To_RIFCS/CityFutures/CustomFunctionsGMD.xsl
rm ./ISO19139_To_RIFCS/EATLAS/CustomFunctionsGMD.xsl
rm ./ISO19139_To_RIFCS/IMAS/CustomFunctionsGMD.xsl
rm ./ISO19139_To_RIFCS/IMOS/CustomFunctionsGMD.xsl
